# Change these parameters

input_dir: /home/aaziz/data/rsv_iseq26/

output_dir: /home/aaziz/analysis/rsv/iseq26_v2/

organism: RSV # options are: FLU or RSV

# these options are only for FLU
subset: False # set to True if ha, na, mp are the only genes of interest
second_assembly: False # secondary assembly - will increase run time substantially

#################################################
#########Do not touch the below parameters#######
#################################################

# trimmomatic location
trimmomatic: bin
# keep going if job fails
keep-going: True