# How to run wfi snakemake pipeline
      # snakemake -j 40 -k
# long form:
# snakemake --snakefile /path/to/wfi/snakefile -j 46 --configfile path/to/output_dir/wfi_config.yaml
# for dry run (to test installation/run params) add -np


####################################
############## Params ##############
####################################

input_dir: /home/amar/Desktop/rsv_test/
output_dir: /home/amar/Desktop/rsv_test/output/

# Organism
# [FLU, RSV, CoV, EBOLA, FLU_AD]
organism: FLU 

# Secondary assembly
# [True, False]
secondary_assembly: True 

# Sequencing technology
# [illumina, ont]
techology: illumina

# FLU Only
# [True, False]
# True = ha, na, mp
# False = all genes
subset: False

