# How to run wfi snakemake pipeline
# snakemake -j 40 -k
# long form:
# snakemake --snakefile /path/to/wfi/snakefile -j 46 --configfile path/to/output_dir/wfi_config.yaml
# for dry run (to test installation/run params) add -np


####################################
############## Params ##############
####################################

input_dir: /Path/To/Input/Directory/
output_dir: /Path/To/Output/Directory/

# Organism
# [FLU, RSV, CoV, EBOLA, FLU_AD]
organism: FLU 

# Secondary assembly
# [True, False]
secondary_assembly: False 

# Sequencing technology
# [illumina, ont, pgm]
technology: illumina

# Trimming mode
# [standard, tile]
# standard uses cutadapt
# tile uses bbduk
trim_prog: standard
# only for trim_prog 'tile'
# only for influenza
# specifies organism specific primers
# [h1, h3]
trim_org: h1


# FLU Only
# [True, False]
# True = ha, na, mp
# False = all genes
subset: False


# experimental - do not touch
# snakemake file pattern
# required patterns = {sample_name} and {sample_number}
pattern_illumina : /{sample_name}_{sample_number}_L{lane_number}_{pair}_001.fastq.gz
pattern_ont : /{sample_name}.fastq.gz
pattern_pgm : /{sample_name}.fastq.gz
