sample_sheet: config/samples.test.csv
output_dir: /Users/aaziz/repos/wfi/tests/output/
adapters: resources/adapters/
use_conda: true

# deprecated 
input_dir: /Users/aaziz/repos/wfi/tests/

# Organism
# Currently supported: [FLU, RSV]
organism: RSV

# Secondary assembly
# [True, False]
secondary_assembly: False

# Sequencing technology
# [illumina, ont, pgm]
technology: illumina

# Trimming mode
# [standard, tiled]
trim_prog: standard

# snakemake file pattern
# required patterns are {sample_name} {sample_number}
pattern_ont : /{sample_name}.fastq.gz
pattern_pgm : /{sample_name}.fastq.gz

# Masking
# set to 0 to disable masking
maskdepth: 20

# plotting 
# [svg, html, png, pdf]
encoding: "svg"

# FLU Only
# [True, False]
# True = ha, na, mp
# False = all genes
subset: False

threads:
  fastp: 2
  ptrimmer: 1
  irma: 10
  nextclade: 10
  ragtag: 2