##### Messesges #####
input_dir: /Users/aaziz/Downloads/wfi_test/
output_dir: /Users/aaziz/Downloads/wfi_output/
adapters: resources/adapters/
use_conda: true

# Organism
# [FLU, RSV, CoV, EBOLA, FLU_AD]
organism: RSV

# Secondary assembly
# [True, False]
secondary_assembly: False

# Sequencing technology
# [illumina, ont, pgm]
technology: illumina

# [standard, tile]
# Trimming mode
# standard uses cutadapt
trim_prog: standard

# FLU Only
# [True, False]
# True = ha, na, mp
# False = all genes
subset: False

# experimental - do not touch
# snakemake file pattern
# required patterns = {sample_name} and {sample_number}
pattern_illumina : /{sample_name}_{sample_number}_L{lane_number}_{pair}_001.fastq.gz
pattern_ont : /{sample_name}.fastq.gz
pattern_pgm : /{sample_name}.fastq.gz

