suppressMessages(library(dplyr))

# get_data_location <- function(base_location, type) {
#   # searches a given directory and returns names table files generated by IRMA.
#   pats <- list(
#     rc = "READ_COUNTS.txt", del = "*-deletions.txt", var = "*-variants.txt",
#     aa = "*-allAlleles", ins = "*-insertions.txt", cov = "*-coverage.txt",
#     ps = "*-paringStats.txt"
#   )
#   
#   if (type %in% pats) {
#     message("Error - Could not find tables to parse from pattern: " + paste0(type))
#   } else {
#     pattern <- pats[[type]]
#   }
#   f <- list.files(base_location, pattern = pattern, full.names = TRUE, recursive = TRUE)
#   return(f)
# }

get_table_data <- function(file_location, org) {
  # returns a list of dataframes read from a list of file names
  if(org == "RSV") {
    dat_out <- list()
    for (f in file_location) {
      df <- read.delim(f, sep = "\t", stringsAsFactors = FALSE)
      if (nrow(df) != 0) {
        splits <- unlist(str_split(string = f, pattern = "/", simplify = F))
        n = length(splits)
        fsplit <- gsub(splits[n], pattern = "-coverage", replacement = "")
        df$sampleID <- paste0(splits[n-2])
        dat_out <- append(dat_out, list(df))
        }
      }
  }
  return(dat_out)
}

calc_stats <- function(coverage_df, org) {
  # coverage_df      : the aa df read in
  # org     : FLU or RSV
  # returns : list(total_mean, total_median, amplicon1_mean, amplicon1_median)
  
  if (toupper(org) == "RSV") {
    
    out <- coverage_df %>%
      summarise(total_mean = round(mean(Consensus_Count)), 
                total_median = round(median(Consensus_Count)),
                amplicon1_mean = round(mean(Consensus_Count[rsv_primer$loc_start[1]:rsv_primer$loc_end[1]])),
                amplicon1_median = round(median(Consensus_Count[rsv_primer$loc_start[1]:rsv_primer$loc_end[1]])),
                amplicon2_mean = round(mean(Consensus_Count[rsv_primer$loc_start[2]:rsv_primer$loc_end[2]])),
                amplicon2_median = round(median(Consensus_Count[rsv_primer$loc_start[2]:rsv_primer$loc_end[2]])),
                amplicon3_mean = round(mean(Consensus_Count[rsv_primer$loc_start[3]:rsv_primer$loc_end[3]])),
                amplicon3_median = round(median(Consensus_Count[rsv_primer$loc_start[3]:rsv_primer$loc_end[3]])),
                amplicon4_mean = round(mean(Consensus_Count[rsv_primer$loc_start[4]:length(Consensus_Count)])),
                amplicon4_median = round(median(Consensus_Count[rsv_primer$loc_start[4]:length(Consensus_Count)]))
                )
    out$sampleID = coverage_df$sampleID[1]
    out$Manual_Check_Required = abs(out$total_mean/out$total_median - 1) > 0.2
    out$MeanDivMed = abs(out$total_mean/out$total_median - 1)
    out = select(out, sampleID, Manual_Check_Required, MeanDivMed, 1:10)
      
  }
  
  if (toupper(org) == "FLU") {
    out = NULL
  }
  
  return(out)
}

base_location = "/media/s_drive/WHOFLU/mol_biol/Illumina folder/2021/Raw Data/iSeq34_Lib2109/Output_RSV/assemblies"

locs = get_data_location(base_location, 'cov')
coverage_data = get_table_data(locs, org = 'RSV')

out = NULL
for (i in coverage_data) {
  tmp = calc_stats(i, org = 'RSV')
  out = rbind(tmp, out)
}
write.table(out, file = "tmp.txt", sep = "\t", row.names = F, quote = F)
